# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 514977c194814a564f05b49aa5fa25a53235ce97dc54df309b722bb9a771fa0e1f289f365854ecb478b14aaee88c25a5b2d2e990beef4b685954c38e86c21934

test:
  secret_key_base: 26f04a24d6203019b2cfce1a1fa939eceb84aee97a61afa54bf8a8998e2762a1fb1670449eb73a3efe859d0c19bba2809372ad4bcfb57828c10879f30efda9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
